name: Docker Build and Deploy

on:
  push:
    branches: [webintegral]  # Cambia 'main' por tu rama 'webintegral'
  pull_request:
    branches: [webintegral]  # Igual aquí

jobs:
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/webintegral'  # Solo en push, no en PRs
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.ref == 'refs/heads/webintegral' }}  # Solo en push
          tags: alejandrox666/desweb_23may:latest  # Reemplaza con tu usuario
          build-args: |
            PORT=4200  # Cambia a 4200 para coincidir con tu configuración

  deploy-to-gh-pages:
    needs: docker-build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/webintegral'  # Solo en push
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true  # Para mantener limpio el historial
